3 файла добавил
KonstantinKlepikov/example-repo pull request #15
Opened 2023-06-04 20:39 UTC by RitoAgent

2023-06-05 13:15 UTC, KonstantinKlepikov requested changes
wait for some changes

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +       print("It's a yeti.")
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +       print("It's a cat!")
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +      print("It's a whale!")
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +      print("It's a human. Or a hairless cat.")
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +        print("It's a tomato")
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +        print("It's a green pepper")
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +        print("I don't know what it is, but only bees can see it")
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +        print("I've never heard of the color", color)
поправь отсутпы - должно быть кратно 4

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +if diff := tweet_limit - len(tweet_string) >= 0: # := оператор присваивания
обрати внимание, что этот оператор доступен только начиная с python 3.10, в более ранних версиях его нет

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/example3.py
> +print('%s' % thing)
данный стиль форматирования строк уже является устаревшим. В дальнейшем тебе в основном придется пользоваться f-строками

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/fin1.py
> +# Присвойте значения True или False переменным small и green. Напишите не-
в данной задаче от тебя требовалось проверить, является ли растения (вклюяая горшок, что бы это ни значило) условиям. Это требует написания цикла вида:

```python
small = True
green = True

if small and green: 
    print('такие-то растения')
elif small and not green:
    ...
...
else:
    ...
```

разберись в задаче и переделай плз

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/fin1.py
> +    print(bool(small),bool(green),'это вишня',',это горошек')
не забывай ставить пробелы после запятых

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/fin2.py
> +kitty2 =  'My kitty cat fell on his'
лишний пробел после знака `=`

2023-06-05 13:15 UTC, KonstantinKlepikov commented on src/fin2.py
> +# Напишите письмо с использованием нового стиля форматирования.
эту задачу можно решить так или с помощью функции format или через f-строки

формат:

```python
print("""some text {0}""".format('this'))
```

f-строки

```python
this = 'this
print(f'some text {this}')
```

жду решения после этой подсказки :)

2023-06-06 17:58 UTC, RitoAgent commented on src/fin2.py
> +# Напишите письмо с использованием нового стиля форматирования.
а можешь еще подсказать в 5.4 Я прочитал задачу но не понимаю как её реализовать в плане замены слов. Че-то не получается + ошибку иногда выдает invalid syntaxis. А задача где нужно было юзать циклы - я сделал через if.else, elif там в главе циклы еще не изучались. Циклы находятся в следующей главе

2023-06-06 21:33 UTC, KonstantinKlepikov commented on src/fin2.py
> +# Напишите письмо с использованием нового стиля форматирования.
@RitoAgent надо будет созвониться, ты покажешь что у тебя не получилось, а я расскажу как можно сделать

2023-06-11 11:21 UTC, KonstantinKlepikov commented on src/fin1.py
> +    print(bool(small),bool(green),'это вишня',',это горошек')
все еще нет пробелов после запятых. Есть соглашение - ставить пробелы после запятых в коде, чтобы было проще читать этот код

2023-06-11 11:22 UTC, KonstantinKlepikov commented on src/example3.py
> +       print("It's a yeti.")
не исправлено

2023-06-11 11:24 UTC, KonstantinKlepikov commented on src/example3.py
> +       print("It's a cat!")
не исправлено

2023-06-11 11:24 UTC, KonstantinKlepikov commented on src/example3.py
> +      print("It's a whale!")
опять

2023-06-11 11:24 UTC, KonstantinKlepikov commented on src/example3.py
> +      print("It's a human. Or a hairless cat.")
и тут

2023-06-11 11:26 UTC, KonstantinKlepikov commented on src/fin2.py
> +kitty2 =  'My kitty cat fell on his'
лишние пробелы не нужно ставить так как это затрудняет чтение кода, исправь

2023-06-11 11:27 UTC, KonstantinKlepikov commented on src/example4.py
> +            print("Eek! An 'x'!")
лишние отступы

2023-06-11 11:28 UTC, KonstantinKlepikov commented on src/example4.py
> +            break
и здесь

2023-06-11 11:32 UTC, KonstantinKlepikov commented on src/forwhile.py
> +list(range(0, 3))
это строка ничего не делает. Если ты хочешь вывести весь список из ренж - тебе надо передать эту конструкцию в print -> вот так print(list(range(3))). Писать range(0, 3) в данном случае не обязательно - если не указана точка старта, ренж стартует с 0.

2023-06-11 11:37 UTC, KonstantinKlepikov commented on src/forwhile.py
> +    print('too low')
для того чтобы это сообщение было выведено при выполнении условия number < guess_me оно должно быть внутри условия if и до continue

вот так:

if number < guess_me:
    print('too low')
    continue

когда поток выполнения программы входит в if в твоем случае, первое что он видит - это оператор continue, который гооворит буквально "выйди из текущей итерации while и начни проходить цикл сначала". Иными словами, если if number < guess_me, то выполняется continue и весь остальной код ниже этого оператора уже не выполняется

2023-06-11 11:39 UTC, KonstantinKlepikov commented on src/forwhile.py
> +    print('found it')
аналогичная проблема тут с оператором breake, разница в том, что break полностью выходит из цикла и потко выполнения передается коду, который находится за пределами цикла и после него. Таким образом после break вообще не выполняется никакой код, находящийся внутри цикла

2023-06-11 11:42 UTC, KonstantinKlepikov commented on src/forwhile.py
> +    #number += 1
вместо этого 

```python
number = range(10)
for guess_me in number:
```

можно написать так:

```python
for guess_me in range(10):
    ...
```

дело в том, что питон создает с помощью range объект, по которому можно итерироваться сразу. Его не нужно предварительно присваивать переменной или получать в виде списка через list(range(10))

2023-06-11 11:44 UTC, KonstantinKlepikov commented on src/forwhile.py
> +    if number == guess_me:
это не будет работать, потому что переменная number ссылается не на число, а на итератор, который возращается от range(10), а вот guess_me - это число из диапазона этого итератора. получается, что ты сравниваешь итератор с числом - они очевидно никогда идентичны не будут :)

2023-06-11 11:46 UTC, KonstantinKlepikov commented
@RitoAgent  добавил комментарии. Пожалуйста исправь все замечания (внимательнее, там не были исправлены большинство замечаний по отступам). Прочитай мои коментарии по циклам и исправь задачу №2 и доделай задачу №3 с учетом этих комментариев. Если тебе что-то непонятно - пиши, я объясню.

2023-06-11 12:06 UTC, RitoAgent commented
Как работает цикл while если в нем выполняетс несколько условий?

2023-06-11 12:20 UTC, KonstantinKlepikov commented
@RitoAgent 

1. поток программы входит в while и проверяет его условие на входе. Условие в цикле всегда только одно. Но это условие может быть сложным выражением, к примеру таким:

```python
while a > 5 and b <= this or function() is None:
  ...
```

2. затем, если условие цикла верно, управление передается коду, который содержится внутри цикла

к примеру цикл

```python
while True:
  ...
```

будет выполняться всегда (что создает бесконечный цикл, можешь попробовать :) )

3. код внутри цикла while выполняется до конца или до операторов continue или breake
4. после этого выполнение передается в начало цикла while. Если условие все еще верно - происходит новый шаг выполнения цикла и так до бесконечности или пока условие не окаждется неверным или пока не бдет выполнен оператор break или пока внутри цикла не поднимется ошибка
5. циклы можно вкладывать один в другой

к примеру

```python
while True:
  while True:
    ...
```

будет выполняться так:

- мы входим во внешний цикл, проеверяем его условие
- т.к. оно всегда True, переходим к коду внутри цикла
- входим во внутренний цикл и проверяем его условие
- т.к. оно True, внутренний цикл будет крутиться бесконечно, т.е. мы никогда из него не выйдем и соответственно проверка внешнего цикла у нас происходит только однократно - на входе, а дальше работает только внутренний

На бесконечных while циклах пишутся графические интерфейсы и, в частности, игры. Отличие for от while в том, что конструкция `for N in THIS` принимает конечную последовательность в качестве THIS и всегда завершается, когда мы добрались до конца этой последовательности. Кроме того, сам for  никаких условий не проверяет - все проверки мы осуществляем самостоятельно внутри цикла for

Так понятно?

2023-06-11 22:18 UTC, KonstantinKlepikov commented
@RitoAgent вот очень хороший набор примеров, который ответит на все твои вопросы:

[конкретно про while](https://www.w3schools.com/python/python_while_loops.asp)

[а тут про for](https://www.w3schools.com/python/python_for_loops.asp)

изучи эти примеры и в целом, если что-то неясно, можншь обращаться к этому [туториалу](https://www.w3schools.com/python/default.asp)

2023-06-13 09:43 UTC, KonstantinKlepikov commented
@RitoAgent опять ты позакрывал коментарии и не исправил отсупы...

```python
number = 0
guess_me = 8
start_text = input('Введите число для поиска: ')
start = int(start_text)
while number < start < guess_me :
    start += 1
    print('too short!', start - 1)
    continue
if start == guess_me :
    print('found it:', guess_me - 1)
else:
    print('oops!')
         
print(" ") 
```

этот код можно переписать без мутных операций вычитания.

```python
number = 0
guess_me = 8
start_text = input('Введите число для поиска: ')
start = int(start_text)
while number < start < guess_me :
    print('too short!', start)
    start += 1
    continue
if start == guess_me :
    print('found it:', start)
else:
    print('oops!')
```

Данный код некорректный. Ты пытаешься изменить переменную, котоаря переопределяется на каждой итерации цикла. Это в данном случае не мешает, но в целом неправильно

вместо 

```python
number = range(10)
for guess_me in number:
    print('too short!', guess_me)
    guess_me += 1
    if guess_me == 5:
        print('found it')
        break
else:
    print('oops')
```

можно сделать так

```python
for guess_me in range(10):
    if guess_me == 5:
        print('found it')
        break
    print('too short!', guess_me)
else:
    print('oops')
```

в этом случае мы сначала проверяем условие на выполнение, а только затем, если мы не вышли из цикла пишем, что ответ неверен и идем на следующую итерацию. Дополнительных операций и переменных не нужно

2023-06-13 09:43 UTC, KonstantinKlepikov approved these changes

2023-06-13 09:43 UTC, merged