Сделал но есть нюансы
KonstantinKlepikov/example-repo pull request #22
Opened 2023-06-21 19:27 UTC by RitoAgent

2023-06-24 00:08 UTC, KonstantinKlepikov commented on src/fin3.py
> +years_list = ["1990", "1991","1992", "1993", "1994", "1995"]
@RitoAgent зачем числа обернуты в кавычки? Так они стали строками. Вполне можно было сделать так

```python
years = [1990, 1991, 1992, 1993, 1994, 1995]
```

или включением

yars = [1990+n for n in range(6)]
```

2023-06-24 00:08 UTC, KonstantinKlepikov commented on src/fin3.py
> +# Используйте списковое включение, чтобы создать список с именем even, в ко-
@RitoAgent так и не решил задачу

2023-06-24 00:21 UTC, KonstantinKlepikov commented on src/setdictionaries.py
> +squares = {}
в данно  задаче от тебя ожидалось создание словаря в одну строку, вот так:

```python
squares = {k: k**2 for k in range(10)}
print(squares)
```

2023-06-24 00:25 UTC, KonstantinKlepikov commented on src/setdictionaries.py
> +# Используйте генератор множества, чтобы создать множество odd из нечетных
тоже самое тут, только вместо словаря - множество

```python
odd = {n for n in range(10) if n % 2 != 0}
```

2023-06-24 00:25 UTC, KonstantinKlepikov commented on src/setdictionaries.py
> +print("Введите число:")
мы же это обсуждали и вроде я показывал чт оу тебя тут чепуха? Почему не исправил?

2023-06-24 00:26 UTC, KonstantinKlepikov commented on src/setdictionaries.py
> +# Используйте включение генератора, чтобы вернуть строку 'Got ' и числа из
все что ниже по прежнему не решено. Какие вопросы?

2023-06-24 00:29 UTC, KonstantinKlepikov requested changes
@RitoAgent доделай задачи. если есть вопросы - задай, я покажу как делать. Посмотри мои коментарии.

2023-06-24 00:32 UTC, KonstantinKlepikov commented
@RitoAgent не забывай делать git fetch git pull в той ветке в которой ты работаешь - надоело на простейших коммитах разгребать конфликты слияний

2023-06-25 19:01 UTC, RitoAgent commented
нужно еще по 7.11 разобраться

2023-06-27 15:48 UTC, KonstantinKlepikov approved these changes

2023-06-27 15:48 UTC, merged